<a href="https://colab.research.google.com/github/RakshanURK20CS1154/Dataset/blob/main/URK20CS1154_ML_LAB_EXP1b_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Stores (2).csv')
df

Branch       City Customer  Gender            Product line  Unit_price  \
0       A     Yangon   Member  Female       Health and beauty       74.69   
1       C  Naypyitaw   Normal  Female  Electronic accessories       15.28   
2       A     Yangon   Normal    Male      Home and lifestyle       46.33   
3       A     Yangon   Member    Male       Health and beauty       58.22   
4       A     Yangon   Normal    Male       Sports and travel       86.31   
5       C  Naypyitaw   Normal    Male  Electronic accessories       85.39   
6       A     Yangon   Member  Female                     NaN       68.84   
7       C  Naypyitaw   Normal  Female                     NaN       73.56   
8       A     Yangon   Member  Female                     NaN       36.26   
9       B   Mandalay   Member  Female                     NaN       54.84   
10      B   Mandalay   Member  Female                     NaN       14.48   
11      B   Mandalay   Member    Male                     NaN       25.51   
12      A     Yangon   Normal  Female  Electronic accessories       46.95   
13      A     Yangon   Normal    Male      Food and beverages       43.19   
14      A     Yangon   Normal  Female       Health and beauty       71.38   
15      B   Mandalay   Member  Female       Sports and travel       93.72   
16      A     Yangon   Member  Female       Health and beauty       68.93   
17    NaN     Yangon   Normal    Male       Sports and travel       72.61   
18    NaN     Yangon   Normal    Male      Food and beverages       54.67   
19    NaN   Mandalay   Normal  Female      Home and lifestyle       40.30   
20    NaN  Naypyitaw   Member    Male  Electronic accessories       86.04   
21    NaN   Mandalay   Normal    Male       Health and beauty       87.98   
22      B   Mandalay   Normal    Male      Home and lifestyle       33.20   
23      A     Yangon   Normal    Male  Electronic accessories       34.56   
24      A     Yangon   Member    Male       Sports and travel       88.63   
25      A     Yangon   Member  Female      Home and lifestyle       52.59   
26      B   Mandalay   Normal    Male     Fashion accessories       33.52   
27      A     Yangon   Normal  Female     Fashion accessories       87.67   
28      B   Mandalay   Normal  Female      Food and beverages       88.36   
29      A     Yangon   Normal    Male       Health and beauty       24.89   
30      B   Mandalay   Normal    Male     Fashion accessories       94.13   
31      B   Mandalay   Member    Male       Sports and travel       78.07   
32      B   Mandalay   Normal    Male       Sports and travel       83.78   
33      A     Yangon   Normal    Male                     NaN       96.58   
34      C  Naypyitaw   Member  Female                     NaN       99.42   
35      C  Naypyitaw   Member  Female                     NaN       68.12   
36    NaN     Yangon   Member    Male                     NaN       62.62   
37    NaN     Yangon   Normal  Female                     NaN       60.88   
38    NaN  Naypyitaw   Normal  Female                     NaN       54.92   
39    NaN   Mandalay   Member    Male                     NaN       30.12   
40    NaN   Mandalay   Member  Female                     NaN       86.72   
41    NaN  Naypyitaw   Member    Male                     NaN       56.11   
42    NaN   Mandalay   Member  Female                     NaN       69.12   
43      C  Naypyitaw   Member  Female                     NaN       98.70   
44      C  Naypyitaw   Member    Male                     NaN       15.37   
45      B   Mandalay   Member  Female  Electronic accessories       93.96   
46      B   Mandalay   Member    Male       Health and beauty       56.69   
47      B   Mandalay   Member  Female      Food and beverages       20.01   
48      B   Mandalay   Member    Male  Electronic accessories       18.93   
49      B   Mandalay   Member    Male  Electronic accessories       18.93   

    Quantity      Tax     Total      Payment    cogs  Rating  Age  \
0     

In [ ]:
null = (df.isnull().sum() / len(df)) * 100
null[null > 0]

Branch          24.0
Product line    36.0
dtype: float64

In [ ]:
for i in range(0, len(null)): 
	if null[i] > 0 and null[i] < 10: 
		col_name = df.columns[i] 
		df[col_name].fillna(df[col_name].mean(), inplace=True) 

# Print dataframe 
print(df.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity      Tax     Total      Payment    cogs  Rating  Age  Quarterly_Tax  Price
0       A     Yangon   Member  Female       Health and beauty       74.69         7  26.1415  548.9715      Ewallet  522.83     9.1   23            210   7469
1       C  Naypyitaw   Normal  Female  Electronic accessories       15.28         5   3.8200   80.2200         Cash   76.40     9.6   23            210   1528
2       A     Yangon   Normal    Male      Home and lifestyle       46.33         7  16.2155  340.5255  Credit card  324.31     7.4   24            210   4633
3       A     Yangon   Member    Male       Health and beauty       58.22         8  23.2880  489.0480      Ewallet  465.76     8.4   26            210   5822
4       A     Yangon   Normal    Male       Sports and travel       86.31        60  30.2085  634.3785      Ewallet  604.17     5.3   30            210   8631
5       C  Naypyitaw   Normal    Male  Electro

In [ ]:
for i in range(0, len(null)): 
	if null[i] > 0: 
		col_name = df.columns[i] 
		df[col_name].fillna(df[col_name].mode(), inplace=True) 

# Print dataframe 
print(df.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity      Tax     Total      Payment    cogs  Rating  Age  Quarterly_Tax  Price
0       A     Yangon   Member  Female       Health and beauty       74.69         7  26.1415  548.9715      Ewallet  522.83     9.1   23            210   7469
1       C  Naypyitaw   Normal  Female  Electronic accessories       15.28         5   3.8200   80.2200         Cash   76.40     9.6   23            210   1528
2       A     Yangon   Normal    Male      Home and lifestyle       46.33         7  16.2155  340.5255  Credit card  324.31     7.4   24            210   4633
3       A     Yangon   Member    Male       Health and beauty       58.22         8  23.2880  489.0480      Ewallet  465.76     8.4   26            210   5822
4       A     Yangon   Normal    Male       Sports and travel       86.31        60  30.2085  634.3785      Ewallet  604.17     5.3   30            210   8631
5       C  Naypyitaw   Normal    Male  Electro

In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.impute import KNNImputer 

imputer = KNNImputer(n_neighbors=2) 

df1 = df.select_dtypes(include=[np.number])
#fitting the imputer object 
imputer.fit(df1) 

#applying the imputer object on the dataset 
imputed_df = imputer.transform(df1) 

# print the new dataframe with imputed missing values 
print(imputed_df)

[[7.469000e+01 7.000000e+00 2.614150e+01 5.489715e+02 5.228300e+02
  9.100000e+00 2.300000e+01 2.100000e+02 7.469000e+03]
 [1.528000e+01 5.000000e+00 3.820000e+00 8.022000e+01 7.640000e+01
  9.600000e+00 2.300000e+01 2.100000e+02 1.528000e+03]
 [4.633000e+01 7.000000e+00 1.621550e+01 3.405255e+02 3.243100e+02
  7.400000e+00 2.400000e+01 2.100000e+02 4.633000e+03]
 [5.822000e+01 8.000000e+00 2.328800e+01 4.890480e+02 4.657600e+02
  8.400000e+00 2.600000e+01 2.100000e+02 5.822000e+03]
 [8.631000e+01 6.000000e+01 3.020850e+01 6.343785e+02 6.041700e+02
  5.300000e+00 3.000000e+01 2.100000e+02 8.631000e+03]
 [8.539000e+01 7.000000e+00 2.988650e+01 6.276165e+02 5.977300e+02
  4.100000e+00 3.200000e+01 2.100000e+02 8.539000e+03]
 [6.884000e+01 6.000000e+00 2.065200e+01 4.336920e+02 4.130400e+02
  5.800000e+00 2.700000e+01 2.100000e+02 6.884000e+03]
 [7.356000e+01 1.000000e+01 3.678000e+01 7.723800e+02 7.356000e+02
  8.000000e+00 3.000000e+01 2.100000e+02 7.356000e+03]
 [3.626000e+01 2.000000e

In [ ]:
df.shape

(50, 15)

In [ ]:
import numpy as np
n = df.select_dtypes(include=[np.number])
print("The number of numerical columns: ",n.shape[1])
c = df.select_dtypes(exclude=[np.number])
print("The number of categorical columns: ",c.shape[1])

The number of numerical columns:  9
The number of categorical columns:  6


In [ ]:
z = n.sub(n.mean()).div(n.std())
#dropping the rows with outlier z-score value > 3 
df_out = n[(z > 3).all(axis=1)] 

#displaying the size of the dataframe 
print(df_out.shape)

(0, 9)


In [ ]:
n1 = n.columns
df2 = df
for i in n1:
    data = df[i] 

    #calculating min and max of the feature 
    min_data = np.min(data) 
    max_data = np.max(data) 

    #rescaling the feature using min-max normalization 
    data_normalized = (data - min_data) / (max_data - min_data) 
    df2[i] = data_normalized
    #displaying result 
print(df2.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity       Tax     Total      Payment      cogs    Rating  Age  Quarterly_Tax     Price
0       A     Yangon   Member  Female       Health and beauty    0.708853  0.101695  0.648460  0.648460      Ewallet  0.648460  0.862069  0.1       0.888372  0.708853
1       C  Naypyitaw   Normal  Female  Electronic accessories    0.009418  0.067797  0.060169  0.060169         Cash  0.060169  0.948276  0.1       0.888372  0.009418
2       A     Yangon   Normal    Male      Home and lifestyle    0.374971  0.101695  0.386857  0.386857  Credit card  0.386857  0.568966  0.2       0.888372  0.374971
3       A     Yangon   Member    Male       Health and beauty    0.514952  0.118644  0.573255  0.573255      Ewallet  0.573255  0.741379  0.4       0.888372  0.514952
4       A     Yangon   Normal    Male       Sports and travel    0.845656  1.000000  0.755647  0.755647      Ewallet  0.755647  0.206897  0.8       0.888372  0.84565

In [ ]:
from sklearn.preprocessing import Binarizer 
import pandas as pd 
for i in n1:
    binarizer = Binarizer(threshold=25) 

    # Binarize the dataset 
    binarizer.fit_transform(df[i].values.reshape(-1,1)) 

    #Print the transformed dataset 
    print(binarizer.fit_transform(df[i].values.reshape(-1,1)))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse=False) 
enc.fit(df)

#Transforming the data 
onehotlabels = enc.transform(df)
print(onehotlabels)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [ ]:
def drop_duplicates(df, column):
    # Find the duplicate rows
    duplicate_rows = df[df.duplicated(column, keep=False)]

    # Find the number of unique values in the column
    num_unique_values = len(duplicate_rows[column].unique())

    # Find the number of duplicate rows
    num_duplicate_rows = len(duplicate_rows)

    # Calculate the percentage of rows that are duplicates
    pct_duplicate_rows = num_duplicate_rows / (num_duplicate_rows + num_unique_values)

    # If more than 50% of the rows are duplicates, drop the duplicate rows
    if pct_duplicate_rows > 0.5:
        return df.drop_duplicates(subset=column)
    else:
        return df


In [ ]:
df = pd.get_dummies (columns=['Branch'])
print df

TypeError: ignored